<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 src/lib/scenes/pc/scene.gltf --transform
Author: Manu.Vision (https://sketchfab.com/manu.vision)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/day-56-1-scan-a-day-workstation-284871764a654d0aa89d3bae3e2bd02a
Title: Day 56 - 1 Scan A Day - Workstation
-->

<script>
  import { Group } from 'three'
  import { extend, T, forwardEventHandlers, useThrelte } from '@threlte/core'
  import { interactivity, useGltf } from '@threlte/extras'
	import Camera from './Camera.svelte';
   

  const { target } = interactivity()
  target.set(document.getElementById('int-target') ?? undefined)
  
  export const ref = new Group()

  const gltf = useGltf('static/pc.glb', { useDraco: true })

  const component = forwardEventHandlers();
</script>


<Camera />

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.main} rotation={[-Math.PI / 2, 0, 0]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
